"""empty message

Revision ID: 31dc1bb89225
Revises: 
Create Date: 2021-09-13 20:01:13.728299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dc1bb89225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modify_date', sa.DateTime(), nullable=True))
    op.alter_column('user', 'create_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('user', 'modify_date')
    # ### end Alembic commands ###
