"""empty message

Revision ID: d65677808572
Revises: 
Create Date: 2021-09-11 21:17:52.059842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65677808572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modify_date')
    op.drop_column('user', 'create_date')
    # ### end Alembic commands ###
